name: Fenrir Code Quality
run-name: ${{ github.actor }} is running code quality assurance
on:
  pull_request:
  push:
    branches: master

jobs:
  cs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Install packages
      run: composer install --no-progress
    - name: Run CS
      run: composer cs

  phpmd:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Install packages
      run: composer install --no-progress
    - name: Run MD
      run: composer md

  namespace-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Verify namespaces
      run: bash util/verify-namespacing.sh

  syntax-check:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Verify linting for ${{ matrix.php }}
        run: ./util/verify-namespacing.sh
